# Generated by Django 5.0.7 on 2024-07-22 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('origin', models.CharField(blank=True, max_length=255, null=True)),
                ('invite_link', models.URLField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255)),
                ('serialized', models.CharField(max_length=255)),
                ('message_sent', models.BooleanField(default=False)),
                ('collection_date', models.DateTimeField(auto_now_add=True)),
                ('send_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('number', 'serialized')},
            },
        ),
    ]
