# Generated by Django 5.0.7 on 2024-07-22 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0002_rename_contact_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='message_sent',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
