# Generated by Django 5.0.7 on 2024-07-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0003_alter_contacts_message_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='status_connect',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
